application:
  version: 1.0.0-SNAPSHOT
server:
  port: 8090
  servlet:
    context-path: /pushserver
  # 以下是undertow内嵌服务器的配置项
  undertow:
    buffer-size: 1024
    direct-buffers: true
    eager-filter-init: true
    io-threads: 8
    worker-threads: 128
    max-http-post-size: -1B

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    redis:
      enabled: false

eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10
    enabled: false
    serviceUrl:
      defaultZone: http://10.100.1.19:8761/eureka/
  instance:
    preferIpAddress: false

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  output:
    ansi:
      enabled: always
  application:
    name: LBS-PUSH-SERVER
  data:
    mongodb:
      host: 192.168.3.168
      port: 27017
      username: zongwei
      # 加单引号解决prohibited character at position 0的问题
      password: '123456'
      # 指定操作的数据库
      database: PUSH_SERVER
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# logback配置文件路径
#logging:
#  config: file:${NOTIFY_CONFIG_PATH}/logback.xml
